name: Sync Fork

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync main branch
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          upstream_repository: leaker/xlsx
          target_repository: go-xlsx/xlsx
          upstream_branch: main
          target_branch: main
          force: true
          tags: true

      - name: sync v1 branch
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          upstream_repository: leaker/xlsx
          target_repository: go-xlsx/xlsx
          upstream_branch: v1
          target_branch: v1
          force: true
          tags: true
